# Generated by Django 5.0 on 2023-12-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company',
            new_name='company_id',
        ),
    ]
